'use client';
import {useState,type FormEvent} from 'react';
import {getAuthClient} from '@/integrations/supabase-browser';
import {useAuth} from './auth-provider';
import {PageHeading,Panel,TextLink,Badge} from './ui';
export function Access(){
 const {session,ready}=useAuth();const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');const form=new FormData(e.currentTarget);try{const {error}=await getAuthClient().auth.signInWithPassword({email:String(form.get('email')).trim(),password:String(form.get('password'))});if(error)setMessage('No pudimos iniciar sesión. Revisá el email y la contraseña de tu acceso a la Agencia.');}catch{setMessage('No se pudo conectar. Intentá nuevamente.');}finally{setBusy(false);}}
 async function signOut(){setBusy(true);const {error}=await getAuthClient().auth.signOut({scope:'local'});if(error)setMessage('No se pudo cerrar la sesión. Intentá nuevamente.');setBusy(false);}
 return <><PageHeading eyebrow="TU INFORMACIÓN PRIVADA" title="Acceso a la Agencia" description="Entrá con tu acceso habilitado para guardar y recuperar tu información entre dispositivos." action={<Badge tone="green">Conexión Supabase</Badge>}/>{message&&<div className="warning" role="alert">{message}</div>}{!ready?<p role="status">Revisando sesión…</p>:session?<Panel title="Sesión iniciada"><div className="info-form"><p>{session.user.email}</p><p>La copia privada pertenece a este usuario. Otras cuentas no pueden acceder a ella. El guardado en la nube es manual desde el Centro de información.</p><TextLink href="/informacion">Ir a mi información</TextLink><button className="secondary-button" onClick={()=>void signOut()} disabled={busy}>Cerrar sesión en este equipo</button><p>Cerrar sesión no borra la información que hayas guardado localmente en este navegador.</p></div></Panel>:<Panel title="Iniciar sesión" subtitle="El acceso a la Agencia se habilita por separado de la cuenta de administración de Supabase."><form onSubmit={submit} className="info-form"><label>Email<input name="email" type="email" autoComplete="username" required maxLength={254}/></label><label>Contraseña<input name="password" type="password" autoComplete="current-password" required maxLength={128}/></label><button className="primary-button" disabled={busy}>{busy?'Ingresando…':'Entrar'}</button><p>Si todavía no tenés un acceso, el administrador debe habilitar tu usuario. No compartas tu contraseña por chat.</p><TextLink href="/informacion">Continuar con carga local</TextLink></form></Panel>}</>;
}
