'use client';
import { ChartNoAxesCombined, Megaphone, ShoppingBag, TrendingUp, Wallet } from 'lucide-react';
import { useBusiness } from './business-provider';
import { Metric,Panel,TextLink } from './ui';
import { SalesChart } from './charts';
import { businessTotals } from '@/services/business-import';
import { formatMoney,formatNumber,formatPercent } from '@/services/finance';
export function BusinessSummary(){
 const {data}=useBusiness();const m=businessTotals(data.daily);const days=[...data.daily].sort((a,b)=>a.fecha.localeCompare(b.fecha));
 return <><div className="demo-strip"><span>Información cargada por vos · Sin conciliación automática</span><TextLink href="/informacion">Administrar información</TextLink></div>{days.length?<><p className="import-period">{days[0].fecha} al {days.at(-1)!.fecha} · {days.length} días informados · ARS netos</p><div className="metrics-grid"><Metric label="Ventas netas" value={formatMoney(m.revenue)} detail="Suma de los días cargados" icon={Wallet}/><Metric label="Pedidos" value={formatNumber(m.orders)} detail="Informados en la carga" icon={ShoppingBag}/><Metric label="Margen de contribución" value={formatPercent(m.margin)} detail="Antes de pauta y costos fijos" icon={ChartNoAxesCombined}/><Metric label="Pauta Meta" value={formatMoney(m.spend)} detail="Inversión informada" icon={Megaphone}/><Metric label="ROAS atribuido" value={m.roas===null?'Sin base':`${formatNumber(m.roas,2)}x`} detail="No indica incrementalidad" icon={TrendingUp}/></div><Panel title="Ventas y publicidad cargadas" subtitle="Se grafican únicamente los días informados; no se completan faltantes con ceros."><SalesChart rows={days.map(d=>({day:d.fecha,sales:d.ventas_netas,spend:d.pauta_meta}))}/><div className="chart-footnote">Ventas: eje izquierdo · Pauta Meta: eje derecho · ARS</div></Panel></>:<Panel title="Cargá tus primeras métricas"><div className="padded-content"><p>Descargá la plantilla de métricas diarias, completala y revisá la importación. Tus números aparecerán acá.</p><TextLink href="/informacion">Ir al centro de información</TextLink></div></Panel>}<div className="two-column"><Panel title="Tu base de información"><dl className="settings-list"><div><dt>Productos</dt><dd>{data.products.length}</dd></div><div><dt>Documentos y notas</dt><dd>{data.documents.length}</dd></div><div><dt>Perfil del negocio</dt><dd>{data.profile.description?'Cargado':'Por completar'}</dd></div><div><dt>Guardado</dt><dd>En este navegador</dd></div></dl></Panel><Panel title="Preparación para el análisis"><div className="padded-content"><p>Las métricas se calculan en código a partir de tu carga. El Director todavía usa ejemplos y no analiza esta información. Las recomendaciones, campañas y experimentos de las otras secciones siguen siendo demo.</p><p>No se calcula utilidad sin costos fijos y demás gastos, ni distribución de canales sin datos conciliados.</p><TextLink href="/configuracion">Ver integraciones pendientes</TextLink></div></Panel></div></>;
}
