'use client';
import {useEffect,useState} from 'react';
import {Cloud,CloudUpload,RefreshCw} from 'lucide-react';
import {useAuth} from './auth-provider';
import {useBusiness} from './business-provider';
import {getAuthClient} from '@/integrations/supabase-browser';
import type {BusinessSnapshot} from '@/db/business-store';
import {businessSchema} from '@/schemas/business';
import {Panel,TextLink,Badge} from './ui';
async function request(method:'GET'|'POST',body?:unknown){
 const {data:{session}}=await getAuthClient().auth.getSession();if(!session)throw new Error('Iniciá sesión para acceder a tu copia privada.');
 const response=await fetch('/api/informacion',{method,headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store'});
 const result=await response.json();if(!response.ok)throw new Error(result.error||'No se pudo completar la operación.');
 const snapshot=result.snapshot as BusinessSnapshot|null;if(snapshot)businessSchema.parse(snapshot.data);return snapshot;
}
export function CloudBackup(){
 const {session,ready}=useAuth();const {data,save}=useBusiness();const [snapshot,setSnapshot]=useState<BusinessSnapshot|null>(null),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[problem,setProblem]=useState(''),[message,setMessage]=useState(''),[pending,setPending]=useState<'upload'|'restore'|null>(null);
 useEffect(()=>{let active=true;setSnapshot(null);setLoaded(false);setPending(null);setProblem('');setMessage('');if(session)request('GET').then(value=>{if(active){setSnapshot(value);setLoaded(true);}}).catch(e=>{if(active)setProblem(e.message);});return()=>{active=false;};},[session?.user.id]);
 async function refresh(){setBusy(true);setProblem('');setPending(null);try{setSnapshot(await request('GET'));setLoaded(true);}catch(e){setProblem(e instanceof Error?e.message:'No se pudo leer la copia.');}finally{setBusy(false);}}
 async function confirm(){setBusy(true);setProblem('');setMessage('');try{if(pending==='upload'){setSnapshot(await request('POST',{data,expectedRevision:snapshot?.revision??0}));setMessage('Copia privada guardada en Supabase.');}else if(pending==='restore'&&snapshot){save(snapshot.data);setMessage('Copia privada cargada y guardada en este navegador.');}setPending(null);}catch(e){setProblem(e instanceof Error?e.message:'No se pudo completar la operación.');}finally{setBusy(false);}}
 return <Panel title="Copia privada entre dispositivos" subtitle="Guardado manual. Después de modificar tu información, guardá una nueva copia privada." action={<Cloud size={21}/>}><div className="info-form">{!ready?<p>Revisando acceso…</p>:!session?<><p>Entrá para guardar una copia protegida por usuario y recuperarla desde otro equipo. La información local no se envía automáticamente.</p><TextLink href="/acceso">Iniciar sesión</TextLink></>:<><div className="info-overview"><span>{session.user.email}</span><Badge tone={snapshot?'green':'orange'}>{snapshot?'Copia privada disponible':'Sin copia privada'}</Badge><TextLink href="/acceso">Mi acceso</TextLink></div>{snapshot?<p>Revisión {snapshot.revision} · {snapshot.data.products.length} productos · {snapshot.data.daily.length} días · {snapshot.data.documents.length} documentos. Guardada: {new Date(snapshot.updatedAt!).toLocaleString('es-AR')}.</p>:<p>{loaded?'Todavía no hay una copia privada para este usuario.':'Consultando tu copia privada…'}</p>}<div className="cloud-actions"><button className="secondary-button" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={16}/>Revisar copia privada</button><button className="primary-button" disabled={busy||!loaded} onClick={()=>{setPending('upload');setMessage('');}}><CloudUpload size={16}/>Guardar copia privada</button><button className="secondary-button" disabled={busy||!snapshot} onClick={()=>{setPending('restore');setMessage('');}}>Usar copia privada en este navegador</button></div>{pending&&<div className="cloud-confirm"><h3>{pending==='upload'?'Guardar la información de este navegador en Supabase':'Reemplazar la información local con la copia privada'}</h3><p>{pending==='upload'?`Se guardarán ${data.products.length} productos, ${data.daily.length} días y ${data.documents.length} documentos. Esto reemplaza la copia privada de tu usuario.`:'Esto reemplaza el perfil, productos, métricas y documentos de este navegador. Podés descargar primero un respaldo local.'}</p><div className="cloud-actions"><button className="secondary-button" disabled={busy} onClick={()=>setPending(null)}>Cancelar</button><button className="primary-button" disabled={busy} onClick={()=>void confirm()}>{busy?'Guardando…':'Confirmar operación'}</button></div></div>}</>}{problem&&<div className="warning" role="alert">{problem}</div>}{message&&<p role="status">{message}</p>}</div></Panel>;
}
