'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Check, ChevronRight, FileText, LoaderCircle, LockKeyhole, Send, Sparkles } from 'lucide-react';
import { useDemo } from './demo-provider';
import { agentInfo } from '@/services/demo-data';
import { runDemoDirector } from '@/workflows/demo-director';
import { Badge, DemoNote, PageHeading, Panel, TextLink } from './ui';
import { formatMoney,formatPercent } from '@/services/finance';
import type { DecisionCase } from '@/schemas/decision';
export function Director(){
 const {question,setQuestion,addCase,ready}=useDemo();const [step,setStep]=useState(-1);const [result,setResult]=useState<DecisionCase|null>(null);const running=step>=0&&step<4;const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const input=useRef('');
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 function run(e:React.FormEvent){e.preventDefault();if(running||!question.trim()||!ready)return;input.current=question.trim();setResult(null);setStep(0);advance(0);}
 function advance(n:number){timer.current=setTimeout(()=>{if(n<3){setStep(n+1);advance(n+1);}else{const report=runDemoDirector(input.current);addCase(report.decisionCase,report.recommendations);setResult(report.decisionCase);setStep(4);}},650);}
 return <><PageHeading eyebrow="COORDINACIÓN" title="Preguntale al Director" description="Un objetivo, cuatro perspectivas y un expediente para cada decisión." action={<Badge tone="blue">Simulación guiada</Badge>}/><DemoNote>El Director de esta V0 usa respuestas de ejemplo. Todavía no consulta modelos de IA ni cuentas reales.</DemoNote>
 <div className="director-page-grid"><div><Panel title="¿Qué querés resolver hoy?" subtitle="El Director mantiene el objetivo y consulta al equipo."><form onSubmit={run} className="question-form"><textarea aria-label="Objetivo para el Director" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="¿Qué cambiarías hoy para aumentar las ventas sin bajar margen?" maxLength={600} rows={4} disabled={running}/><div className="question-actions"><small>{question.length}/600</small><button className="primary-button" disabled={running||!question.trim()||!ready}>{running?<LoaderCircle className="spin" size={16}/>:<Sparkles size={16}/>} {running?'Consultando al equipo…':'Simular análisis'}</button></div></form><div className="suggestions">{['¿Cómo vender más sin bajar margen?','¿Puedo aumentar el presupuesto de Meta?','¿Qué mejorar en la landing del Circuito?'].map(q=><button key={q} onClick={()=>setQuestion(q)} disabled={running}>{q}<ArrowRight size={14}/></button>)}</div></Panel>
 <Panel title="Mesa de especialistas" subtitle="Consulta coordinada · Meta Ads → Finanzas → Analytics → CRO"><div className="consultation-list" aria-live="polite">{agentInfo.map((a,i)=><div className={`consultation ${step===i?'working':''}`} key={a.id}><span className={`agent-avatar ${a.tone}`}>{a.initials}</span><div><h3>{a.name}</h3><p>{step>i?a.finding:a.role}</p></div>{step===i?<LoaderCircle className="spin" size={19}/>:step>i?<Check size={19} className="positive"/>:<span className="muted">En espera</span>}</div>)}</div></Panel>
 {result&&<Panel title="La prioridad: decidir con una base confiable" action={<Badge tone="green">Expediente creado</Badge>}><div className="analysis-result" role="status"><p>Para el objetivo “{result.objective}”, este ejemplo prioriza mejorar la conversión y resolver la medición antes de escalar la inversión.</p><div className="result-metrics"><div><span>Ventas base · demo</span><strong>{formatMoney(result.baseline.revenue)}</strong></div><div><span>Margen antes de pauta</span><strong>{formatPercent(result.baseline.contributionRate)}</strong></div></div>{result.findings.map(f=><p key={f}><Check size={16}/>{f}</p>)}<div className="warning"><LockKeyhole size={18}/><span>{result.contradictions[0]}</span></div><div className="result-links"><TextLink href="/recomendaciones">Revisar recomendaciones</TextLink><TextLink href="/memoria">Abrir expediente</TextLink></div></div></Panel>}
 </div><div><Panel title="Cómo se toma una decisión"><ol className="process-list"><li><span>01</span><div><h3>Datos y métricas</h3><p>Una base compartida. Los números se calculan en código.</p></div></li><li><span>02</span><div><h3>Análisis especializado</h3><p>Cada especialista aporta evidencia dentro de su área.</p></div></li><li><span>03</span><div><h3>Validación y bloqueos</h3><p>Analytics y Finanzas pueden frenar una recomendación.</p></div></li><li><span>04</span><div><h3>Tu aprobación</h3><p>El Director prioriza. Vos decidís qué se implementa.</p></div></li></ol></Panel><div className="side-note"><FileText size={22}/><h3>Cada decisión deja memoria</h3><p>Objetivo, fuentes, conclusiones, contradicciones y aprobaciones, en un mismo expediente.</p><small>En esta V0, los expedientes se guardan en este navegador.</small></div></div></div></>;
}
