'use client';
import { useState } from 'react';
import { ChartNoAxesCombined, Landmark, Scale, Target } from 'lucide-react';
import { Badge, DemoNote, Metric, PageHeading, Panel } from './ui';
import { calculateFinance,formatMoney,formatNumber,formatPercent } from '@/services/finance';
export function FinanceView(){
 const [sales,setSales]=useState(30000000);const [margin,setMargin]=useState(38);const [fixed,setFixed]=useState(6300000);const [spend,setSpend]=useState(3000000);
 const model=(revenue:number)=>calculateFinance({revenue,variableCosts:Math.round(revenue*(1-margin/100)),fixedCosts:fixed,adSpend:spend,orders:Math.round(revenue/110000),attributedRevenue:revenue*.52});const m=model(sales);
 return <><PageHeading eyebrow="ESPECIALISTA · FINANZAS" title="Crecer con rentabilidad" description="Números calculados en código. Una base clara para decidir cuánto invertir." action={<Badge tone="green">Motor determinístico</Badge>}/><DemoNote>Simulador mensual con supuestos ficticios. Importes netos de IVA, descuentos y devoluciones; costos variables sin pauta.</DemoNote><div className="metrics-grid four"><Metric label="Margen de contribución" value={formatPercent(m.contributionRate)} detail={`${formatMoney(m.contribution)} antes de pauta`} icon={ChartNoAxesCombined}/><Metric label="Punto de equilibrio" value={formatMoney(m.breakEvenRevenue)} detail="Incluye costos fijos y pauta" icon={Target}/><Metric label="Resultado operativo" value={formatMoney(m.operatingProfit)} detail="Antes de Ganancias e intereses" icon={Landmark}/><Metric label="ROAS de contribución" value={m.contributionRoasFloor?`${formatNumber(m.contributionRoasFloor,2)}x`:'Sin base'} detail="Piso teórico; no cubre costos fijos" icon={Scale}/></div>
 <div className="finance-grid"><Panel title="Tu escenario mensual" subtitle="Mové los supuestos y compará el resultado."><div className="scenario-controls"><label>Ventas netas previstas<strong>{formatMoney(sales)}</strong><input aria-label="Ventas netas previstas" type="range" min={0} max={60000000} step={1000000} value={sales} onChange={e=>setSales(Number(e.target.value))}/><span className="range-labels"><small>$0</small><small>$60 M</small></span></label><label>Margen antes de pauta<strong>{margin}%</strong><input aria-label="Margen antes de pauta" type="range" min={0} max={80} step={1} value={margin} onChange={e=>setMargin(Number(e.target.value))}/></label><div className="input-pair"><label>Costos fijos · ARS<input type="number" min={0} max={100000000} value={fixed} onChange={e=>setFixed(Math.max(0,Math.min(100000000,Number(e.target.value))))}/></label><label>Pauta mensual · ARS<input type="number" min={0} max={100000000} value={spend} onChange={e=>setSpend(Math.max(0,Math.min(100000000,Number(e.target.value))))}/></label></div></div></Panel><Panel title="Qué dice este escenario"><div className="finance-result"><Badge tone={m.operatingProfit>0?'green':'orange'}>{m.operatingProfit>0?'Supera el equilibrio':'Por debajo del equilibrio'}</Badge><strong className={m.operatingProfit>0?'positive':'negative'}>{formatMoney(m.operatingProfit)}</strong><p>Resultado operativo mensual con {formatPercent(m.contributionRate)} de contribución, {formatMoney(fixed)} de costos fijos y {formatMoney(spend)} de pauta.</p><div className="formula">Ventas − costos variables − costos fijos − pauta</div><p className="small-copy">El piso de ROAS usa 1 / margen. El techo de CAC de contribución sería {formatMoney(m.contributionCacCeiling)} por pedido, suponiendo que todos fueran clientes nuevos. No es un CAC máximo rentable: faltan costos fijos por cliente y beneficio objetivo.</p></div></Panel></div>
 <Panel title="Comparación de escenarios" subtitle="Mismos supuestos; cambia únicamente la facturación"><div className="table-scroll"><table><thead><tr><th>Ventas netas</th><th>Contribución</th><th>Costos fijos</th><th>Pauta</th><th>Resultado operativo</th></tr></thead><tbody>{[20,25,30,35,40].map(n=>{const row=model(n*1000000);return <tr key={n}><td><strong>{formatMoney(row.revenue)}</strong></td><td>{formatMoney(row.contribution)}</td><td>{formatMoney(fixed)}</td><td>{formatMoney(spend)}</td><td className={row.operatingProfit>=0?'positive':'negative'}><strong>{formatMoney(row.operatingProfit)}</strong></td></tr>;})}</tbody></table></div></Panel><div className="methodology"><h3>Base de cálculo</h3><p>Margen = (ventas netas − costos variables sin pauta) / ventas netas. Equilibrio = (costos fijos + pauta) / margen. Si el margen es cero o negativo, no existe equilibrio bajo estos supuestos. No se estima utilidad neta sin impuestos, intereses y otros conceptos completos.</p></div></>;
}
