'use client';
import {useState,type FormEvent} from 'react';
import {Database,Download,FileText,Package,Upload} from 'lucide-react';
import {businessSchema,type BusinessData,type Daily,type Product} from '@/schemas/business';
import {parseBusinessCsv,templates,businessTotals} from '@/services/business-import';
import {formatMoney} from '@/services/finance';
import {useBusiness} from './business-provider';
import {Badge,DemoNote,PageHeading,Panel,TextLink} from './ui';
type Pending={kind:'daily';rows:Daily[]}|{kind:'products';rows:Product[]}|{kind:'backup';data:BusinessData};
function download(name:string,text:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function Information(){
 const {data,ready,error,save}=useBusiness();const [tab,setTab]=useState('profile');const [message,setMessage]=useState('');const [problem,setProblem]=useState('');const [pending,setPending]=useState<Pending|null>(null);const [csv,setCsv]=useState('');const [kind,setKind]=useState<'daily'|'products'>('daily');
 function attempt(action:()=>void){setProblem('');setMessage('');try{action();}catch(e){setProblem(e instanceof Error?e.message:'No se pudo completar la operación.');}}
 function persist(next:BusinessData){save(next);setMessage('Información guardada en este navegador. Podés descargar un respaldo.');}
 function profileSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);attempt(()=>persist({...data,profile:{name:String(form.get('name')),website:String(form.get('website')),description:String(form.get('description')),audience:String(form.get('audience')),goals:String(form.get('goals'))}}));}
 function review(source:string){attempt(()=>setPending(kind==='daily'?{kind,rows:parseBusinessCsv('daily',source)}:{kind,rows:parseBusinessCsv('products',source)}));}
 async function read(file:File|undefined,backup=false){if(!file)return;setPending(null);setProblem('');try{if(file.size>(backup?2_000_000:1_000_000))throw new Error('El archivo supera el tamaño permitido.');const content=await file.text();if(backup){setPending({kind:'backup',data:businessSchema.parse(JSON.parse(content))});}else{setCsv(content);review(content);}}catch(e){setProblem(e instanceof Error?e.message:'No se pudo leer el archivo.');}}
 function confirm(){attempt(()=>{if(!pending)return;persist(pending.kind==='backup'?pending.data:{...data,[pending.kind]:pending.rows});setPending(null);setCsv('');});}
 function documentSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();const formElement=e.currentTarget;const form=new FormData(formElement);attempt(()=>{const next=businessSchema.parse({...data,documents:[...data.documents,{id:crypto.randomUUID(),title:String(form.get('title')),category:String(form.get('category')),text:String(form.get('text'))}]});persist(next);formElement.reset();});}
 if(!ready)return <p role="status">Cargando información guardada…</p>;
 return <><PageHeading eyebrow="TU BASE DE TRABAJO" title="Centro de información" description="Prepará la información de Purfect para que el equipo trabaje con una base ordenada." action={<Badge tone="blue">Carga manual · Local</Badge>}/><DemoNote>La información se guarda solo en este navegador y en esta dirección web. No se envía a IA ni se sincroniza. Usá información de negocio sin claves ni datos personales de clientes y descargá respaldos.</DemoNote>{error&&<div className="warning" role="alert">{error}</div>}<div className="info-overview"><span><Package size={17}/>{data.products.length} productos</span><span><Database size={17}/>{data.daily.length} días</span><span><FileText size={17}/>{data.documents.length} documentos</span><button className="secondary-button" onClick={()=>download('purfect-informacion.json',JSON.stringify(data,null,2),'application/json')}><Download size={16}/>Descargar respaldo</button></div><div className="filter-tabs" role="group" aria-label="Secciones de información">{[['profile','Negocio'],['data','Productos y métricas'],['documents','Documentos'],['backup','Restaurar respaldo']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>{setTab(id);setPending(null);setMessage('');setProblem('');}}>{label}</button>)}</div>{problem&&<div role="alert" className="warning import-error">{problem}</div>}{message&&<div role="status" className="demo-strip">{message}</div>}
 {tab==='profile'&&<Panel title="Contexto del negocio" subtitle="Esta información se conserva separada de las simulaciones del Director."><form key={data.updatedAt} className="info-form" onSubmit={profileSubmit}><div className="two-column"><label>Nombre del negocio<input name="name" maxLength={300} required defaultValue={data.profile.name}/></label><label>Sitio web<input name="website" type="url" maxLength={300} defaultValue={data.profile.website}/></label></div><label>Qué vendemos y qué nos diferencia<textarea name="description" maxLength={5000} rows={4} defaultValue={data.profile.description} placeholder="Productos, propuesta de valor, materiales, calidad y diferenciación…"/></label><label>A quién le vendemos<textarea name="audience" maxLength={5000} rows={3} defaultValue={data.profile.audience} placeholder="Clientes ideales, necesidades y motivos de compra…"/></label><label>Objetivos y límites del negocio<textarea name="goals" maxLength={5000} rows={3} defaultValue={data.profile.goals} placeholder="Objetivos, márgenes a cuidar, capacidad de producción y restricciones…"/></label><button className="primary-button" disabled={!!error}>Guardar perfil</button></form></Panel>}
 {tab==='data'&&<><Panel title="Importar productos o métricas" subtitle="Descargá una plantilla, reemplazá la fila de ejemplo y subí un CSV UTF-8. Cada importación reemplaza la tabla elegida después de confirmarla."><div className="info-form"><label>Tipo de información<select aria-label="Tipo de información" value={kind} onChange={e=>{setKind(e.target.value as typeof kind);setPending(null);setCsv('');}}><option value="daily">Métricas diarias</option><option value="products">Productos</option></select></label><button className="secondary-button" onClick={()=>download(`plantilla-${kind==='daily'?'metricas':'productos'}.csv`,templates[kind],'text/csv;charset=utf-8')}><Download size={16}/>Descargar plantilla</button><p>{kind==='daily'?'Una fila por fecha. Ventas netas de IVA, descuentos y devoluciones; costos variables sin pauta. Meta se informa por separado y su atribución no se suma a ventas. Máximo 3660 días.':'Una fila por SKU. Precio neto de IVA, costo variable por unidad sin pauta y stock entero. Máximo 2000 productos.'}</p><p>Importes en ARS, sin símbolo ni separador de miles, con punto decimal. Fechas AAAA-MM-DD. Se admite coma o punto y coma como separador.</p><label>Seleccionar CSV<input key={kind} type="file" accept=".csv,text/csv" onChange={e=>void read(e.target.files?.[0])}/></label><label>O pegar el contenido CSV<textarea aria-label="Contenido CSV" value={csv} onChange={e=>{setCsv(e.target.value);setPending(null);}} rows={5} maxLength={1_000_000} spellCheck={false} placeholder={templates[kind]}/></label><button className="primary-button" onClick={()=>review(csv)} disabled={!csv.trim()||!!error}><Upload size={16}/>Revisar importación</button></div></Panel>{!pending&&<div className="two-column"><Panel title="Catálogo cargado"><div className="padded-content">{data.products.length?<><p>{data.products.length} productos. Primeros 5:</p>{data.products.slice(0,5).map(p=><p key={p.sku}>{p.sku} · {p.nombre} · {formatMoney(p.precio_neto)}</p>)}</>:<p>Todavía no hay productos cargados.</p>}</div></Panel><Panel title="Métricas cargadas"><div className="padded-content"><p>{data.daily.length} días · Ventas: {formatMoney(businessTotals(data.daily).revenue)}</p><TextLink href="/">Ver mis indicadores</TextLink></div></Panel></div>}</>}
 {tab==='documents'&&<><Panel title="Agregar un documento o nota" subtitle="Guardá el contenido de marca, productos, promociones, operaciones o investigación. Podés copiar el texto de tus documentos; los PDF y Word aún no se procesan."><form className="info-form" onSubmit={documentSubmit}><div className="two-column"><label>Título<input name="title" maxLength={300} required placeholder="Ej. Condiciones de envío"/></label><label>Categoría<select name="category">{['Marca','Productos','Promociones','Operaciones','Investigación'].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Contenido<textarea name="text" rows={8} required maxLength={50000} placeholder="Pegá acá la información que querés conservar…"/></label><button className="primary-button" disabled={!!error||data.documents.length>=50}>Guardar documento</button><p>Hasta 50 documentos de 50.000 caracteres, con un límite total de 2 MB.</p></form></Panel>{data.documents.map(d=><details className="case-card" key={d.id}><summary><FileText size={19}/><div><h2>{d.title}</h2><p>{d.category} · {d.text.length} caracteres</p></div></summary><div className="case-body"><p className="document-text">{d.text}</p></div></details>)}</>}
 {tab==='backup'&&<Panel title="Restaurar una copia de tu información" subtitle="Elegí un respaldo JSON descargado desde esta aplicación. Revisaremos el contenido antes de reemplazar lo guardado."><div className="info-form"><label>Seleccionar respaldo<input type="file" accept=".json,application/json" onChange={e=>void read(e.target.files?.[0],true)}/></label><p>La restauración reemplaza perfil, productos, métricas y documentos. Descargá primero una copia de la información actual.</p></div></Panel>}
 {pending&&<section className="panel import-review" aria-label="Revisión de importación"><h2>Revisá antes de guardar</h2>{pending.kind==='backup'?<p>Respaldo de {pending.data.profile.name}: {pending.data.products.length} productos, {pending.data.daily.length} días y {pending.data.documents.length} documentos.</p>:<><p>{pending.rows.length} filas válidas. Se reemplazarán {data[pending.kind].length} filas guardadas de {pending.kind==='daily'?'métricas':'productos'}. Las demás secciones se conservan.</p><div className="table-scroll"><table><thead><tr>{Object.keys(pending.rows[0]).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{pending.rows.slice(0,5).map((r,i)=><tr key={i}>{Object.values(r).map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div><p>Vista previa de hasta 5 filas. La validación revisó todas las filas.</p></>}<div className="dialog-actions"><button className="secondary-button" onClick={()=>setPending(null)}>Cancelar importación</button><button className="primary-button" disabled={!!error} onClick={confirm}>Confirmar y guardar</button></div></section>}
 </>;
}
