'use client';
import { useEffect, useRef, useState } from 'react';
import { Check, ChevronDown, LockKeyhole, ShieldCheck, X } from 'lucide-react';
import { useDemo } from './demo-provider';
import { Badge, DemoNote, PageHeading } from './ui';
import { statusLabels } from '@/policies/decisions';
import type { Recommendation } from '@/schemas/decision';
export function Recommendations(){
 const {data,ready,decide}=useDemo();const [filter,setFilter]=useState('all');const [selected,setSelected]=useState<Recommendation|null>(null);const [message,setMessage]=useState('');const dialog=useRef<HTMLDialogElement>(null);
 const counts={all:data.recommendations.length,pending:data.recommendations.filter(r=>['PROPOSED','VALIDATED'].includes(r.status)).length,blocked:data.recommendations.filter(r=>r.status==='CONFLICTED').length,approved:data.recommendations.filter(r=>r.status==='APPROVED').length};
 const rows=data.recommendations.filter(r=>filter==='all'||(filter==='pending'&&['PROPOSED','VALIDATED'].includes(r.status))||(filter==='blocked'&&r.status==='CONFLICTED')||(filter==='approved'&&r.status==='APPROVED'));
 useEffect(()=>{if(selected)dialog.current?.showModal();else dialog.current?.close();},[selected]);
 function confirm(){if(!selected)return;try{decide(selected.id,'APPROVED',true);setMessage('Aprobación demo guardada. No se ejecutó ninguna acción externa.');setSelected(null);}catch(e){setMessage((e as Error).message);}}
 function update(id:string,status:'VALIDATED'|'REJECTED'){try{decide(id,status);setMessage(status==='REJECTED'?'Recomendación rechazada en la demo.':'Validación demo registrada; queda pendiente de aprobación.');}catch(e){setMessage((e as Error).message);}}
 return <><PageHeading eyebrow="DECISIONES" title="Recomendaciones" description="Del análisis a una acción concreta. Siempre con evidencia y tu aprobación."/><div className="filter-tabs" aria-label="Filtrar recomendaciones">{[['all','Todas'],['pending','Por revisar'],['blocked','Bloqueadas'],['approved','Aprobadas']].map(([v,label])=><button key={v} className={filter===v?'selected':''} onClick={()=>setFilter(v)} aria-pressed={filter===v}>{label}<span>{counts[v as keyof typeof counts]}</span></button>)}</div>{message&&<div className="notice" role="status">{message}<button className="icon-button" aria-label="Cerrar mensaje" onClick={()=>setMessage('')}><X size={16}/></button></div>}
 <div className="rec-cards">{rows.map(r=><article className="panel rec-card" key={r.id}><div className="rec-card-heading"><div><span className="eyebrow">{r.agent} <span>· PRIORIDAD {r.priority.toUpperCase()}</span></span><h2>{r.title}</h2></div><Badge tone={r.status==='CONFLICTED'?'orange':r.status==='APPROVED'?'green':r.status==='REJECTED'?'neutral':'blue'}>{statusLabels[r.status]}</Badge></div><p>{r.description}</p><div className="rec-meta"><div><span>Qué vamos a medir</span><strong>{r.metric}</strong></div><div><span>Siguiente paso</span><strong>{r.nextStep}</strong></div></div><details><summary>Ver evidencia y condiciones<ChevronDown size={16}/></summary><ul>{r.evidence.map(e=><li key={e}>{e}</li>)}</ul><p>Las evidencias son ejemplos de la V0; no validan una decisión comercial real.</p></details>{r.blockers.length>0&&<div className="warning"><LockKeyhole size={18}/><div>{r.blockers.map(b=><p key={b}>{b}</p>)}<small>El Director no puede ignorar estos bloqueos.</small></div></div>}<div className="rec-actions"><span><ShieldCheck size={15}/>Aprobación humana requerida</span><div>{['PROPOSED','VALIDATED','CONFLICTED'].includes(r.status)&&<button className="secondary-button" disabled={!ready} onClick={()=>update(r.id,'REJECTED')}>Rechazar</button>}{r.status==='PROPOSED'&&<button className="primary-button" disabled={!ready} onClick={()=>update(r.id,'VALIDATED')}>Validar en demo</button>}{r.status==='VALIDATED'&&<button className="primary-button" disabled={!ready} onClick={()=>setSelected(r)}><Check size={16}/>Revisar aprobación</button>}{r.status==='CONFLICTED'&&<button className="secondary-button" disabled><LockKeyhole size={15}/>Bloqueada</button>}{r.status==='APPROVED'&&<span className="positive">Aprobada · sin implementar</span>}</div></div></article>)}</div>{!rows.length&&<div className="empty-state"><ShieldCheck size={32}/><h2>No hay recomendaciones en este estado</h2><p>Podés revisar las propuestas o crear un nuevo análisis desde el Director.</p></div>}<DemoNote/>
 <dialog ref={dialog} className="approval-dialog" onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===dialog.current)setSelected(null);}} aria-labelledby="approval-title"><div className="dialog-heading"><span className="insight-icon blue"><ShieldCheck size={23}/></span><button className="icon-button" onClick={()=>setSelected(null)} aria-label="Cerrar aprobación"><X/></button></div><h2 id="approval-title">Aprobar recomendación demo</h2><h3>{selected?.title}</h3><p>Esta aprobación se registra solo en este navegador. No publica anuncios, cambia presupuestos, modifica precios ni edita la tienda.</p><div className="dialog-actions"><button className="secondary-button" onClick={()=>setSelected(null)}>Volver</button><button className="primary-button" onClick={confirm}>Confirmar aprobación demo</button></div></dialog>
 </>;
}
